package com.visco.backend.reports.models.enums;

// Categories of reports that can be generated by the system.
public enum ReportType {
    STOCK_INVENTORY("Reporte de Stock"),
    STOCK_MOVEMENTS("Reporte de Movimientos"),
    CRITICAL_ALERTS("Alertas Críticas"),
    WAREHOUSE_ANALYSIS("Análisis por Almacén"),
    DAILY_RECEIPTS("Recepciones Diarias"),
    DAILY_TRANSFERS("Transferencias Diarias"),
    REQUISITION_FULFILLMENT("Adjudicación de Requisiciones");

    private final String displayName;

    ReportType(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
