spring.application.name=viscosg

spring.datasource.url=jdbc:postgresql://localhost:5433/visco_db
spring.datasource.username=visco_admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100


# JWT
app.jwt.secret=7a8f3c2e1b9d4f6a0e5c8b2d7f1a4e9c3b6d0f5a8e2c7b4d1f6a9e3c0b5d8f2a
app.jwt.expiration-ms=86400000

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juliorubinsky04@gmail.com
spring.mail.password=jixmhmgqywlttqou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Aumentar límite para archivos grandes
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB