package com.visco.backend.reports.services;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.visco.backend.reports.models.dtos.CreateReportRequest;
import com.visco.backend.reports.models.dtos.CreateScheduledReportRequest;
import com.visco.backend.reports.models.dtos.DailyReceiptReportDTO;
import com.visco.backend.reports.models.dtos.DailyReceiptReportKPIs;
import com.visco.backend.reports.models.dtos.ReportAnalyticsDTO;
import com.visco.backend.reports.models.dtos.ReportDTO;
import com.visco.backend.reports.models.dtos.ScheduledReportDTO;
import com.visco.backend.reports.models.dtos.UpdateScheduledReportRequest;
import com.visco.backend.reports.models.entities.Report;
import com.visco.backend.reports.models.entities.ScheduledReport;
import com.visco.backend.reports.models.enums.ReportFormat;
import com.visco.backend.reports.models.enums.ReportStatus;
import com.visco.backend.reports.models.enums.ReportType;
import com.visco.backend.reports.repositories.ReportRepository;
import com.visco.backend.reports.repositories.ScheduledReportRepository;
import com.visco.backend.reports.utils.DateUtils;
import jakarta.persistence.EntityNotFoundException;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Orchestrates report generation, scheduling, and retrieval.
 * Reports are produced in memory and returned as byte[] (no disk persistence).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ReportService {

    private final ReportRepository reportRepository;
    private final ScheduledReportRepository scheduledReportRepository;
    private final ReportGeneratorService reportGeneratorService;
    private final PdfExportService pdfExportService;
    private final ExcelExportService excelExportService;
    private final ObjectMapper objectMapper;

    @Value("${app.reports.max-records-per-export:50000}")
    private int maxRecords;

    public Page<ReportDTO> getReports(Pageable pageable, ReportType type, ReportStatus status) {
        if (type != null && status != null) {
            return reportRepository.findByTypeAndStatus(type, status, pageable).map(this::toDTO);
        }
        if (type != null) {
            return reportRepository.findByType(type, pageable).map(this::toDTO);
        }
        if (status != null) {
            return reportRepository.findByStatus(status, pageable).map(this::toDTO);
        }
        return reportRepository.findAll(pageable).map(this::toDTO);
    }

    public Page<ReportDTO> getReports(Pageable pageable) {
        return reportRepository.findAll(pageable).map(this::toDTO);
    }

    public ReportDTO getReportById(Long id) {
        Report report = reportRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Reporte no encontrado: " + id));
        return toDTO(report);
    }

    /**
     * Generates a report fully in memory. The generated bytes are not stored;
     * a download endpoint can regenerate them on demand from the persisted metadata.
     */
    @Transactional
    public ReportDTO generateReport(CreateReportRequest request, String username) {
        if (request.getStartDate() != null && request.getEndDate() != null
                && request.getStartDate().isAfter(request.getEndDate())) {
            throw new IllegalArgumentException("La fecha de inicio debe ser anterior a la fecha de fin");
        }

        if (request.getType() == ReportType.DAILY_RECEIPTS && request.getWarehouseId() == null) {
            throw new IllegalArgumentException("El almacén es obligatorio para el reporte de Recepciones Diarias");
        }

        Report report = Report.builder()
                .name(request.getName())
                .type(request.getType())
                .status(ReportStatus.PENDING)
                .format(request.getFormat())
                .startDate(request.getStartDate())
                .endDate(request.getEndDate())
                .warehouseId(request.getWarehouseId())
                .categoryId(request.getCategoryId())
                .search(request.getSearch())
                .createdBy(username)
                .active(true)
                .build();

        if (request.getAdditionalFilters() != null && !request.getAdditionalFilters().isEmpty()) {
            try {
                report.setFilters(objectMapper.writeValueAsString(request.getAdditionalFilters()));
            } catch (JsonProcessingException e) {
                log.warn("Could not serialize filters", e);
            }
        }

        report = reportRepository.save(report);

        try {
            report.setStatus(ReportStatus.PROCESSING);
            reportRepository.save(report);

            Map<String, String> metadata = new HashMap<>();
            metadata.put("Generado por", username);
            metadata.put("Tipo", request.getType().getDisplayName());
            metadata.put("Período", DateUtils.formatDate(request.getStartDate()) + " - "
                    + DateUtils.formatDate(request.getEndDate()));

            GeneratedReport result = buildReport(request, metadata);
            report.setRecordCount(result.recordCount);

            byte[] content = result.bytes;
            report.setFileSize((long) content.length);
            report.setFilePath(null);
            report.setStatus(ReportStatus.COMPLETED);
            report.setGeneratedAt(LocalDateTime.now());
            report = reportRepository.save(report);

            log.info("Report generated in memory: {} ({} bytes)", report.getName(), content.length);

        } catch (Exception e) {
            log.error("Error generating report: {}", e.getMessage(), e);
            report.setStatus(ReportStatus.FAILED);
            reportRepository.save(report);
            throw new RuntimeException("Error generando reporte: " + e.getMessage(), e);
        }

        return toDTO(report);
    }

    /**
     * Builds the report content (PDF/Excel) directly in memory.
     * Used by /generate (to compute recordCount + fileSize) and by /download
     * (to return the bytes on demand).
     */
    public byte[] buildReportBytes(Report report) {
        CreateReportRequest request = new CreateReportRequest();
        request.setName(report.getName());
        request.setType(report.getType());
        request.setFormat(report.getFormat());
        request.setStartDate(report.getStartDate());
        request.setEndDate(report.getEndDate());
        // The top-level filter scope is stored in dedicated columns on the
        // Report entity, so we can rebuild the request without touching
        // the user-supplied additionalFilters JSON at all.
        request.setWarehouseId(report.getWarehouseId());
        request.setCategoryId(report.getCategoryId());
        request.setSearch(report.getSearch());
        if (report.getFilters() != null) {
            try {
                Map<String, Object> filters = objectMapper.readValue(report.getFilters(), Map.class);
                request.setAdditionalFilters(filters);
            } catch (Exception e) {
                log.warn("Could not parse stored filters for report {}", report.getId(), e);
            }
        }

        Map<String, String> metadata = new HashMap<>();
        metadata.put("Generado por", report.getCreatedBy() != null ? report.getCreatedBy() : "system");
        metadata.put("Tipo", report.getType().getDisplayName());
        metadata.put("Período", DateUtils.formatDate(report.getStartDate()) + " - "
                + DateUtils.formatDate(report.getEndDate()));

        return buildReportBytes(request, metadata);
    }

    private record GeneratedReport(byte[] bytes, int recordCount) {}

    private GeneratedReport buildReport(CreateReportRequest request, Map<String, String> metadata) {
        try (var baos = new ByteArrayOutputStream()) {
            int recordCount = switch (request.getType()) {
                case STOCK_INVENTORY -> {
                    var data = reportGeneratorService.generateStockReport(
                            request.getStartDate(), request.getEndDate(),
                            request.getCategoryId(), request.getWarehouseId(), request.getSearch());
                    if (data.size() > maxRecords) data = data.subList(0, maxRecords);
                    writeStockReport(baos, request, data, metadata);
                    yield data.size();
                }
                case STOCK_MOVEMENTS -> {
                    var data = reportGeneratorService.generateMovementReport(
                            request.getStartDate(), request.getEndDate(),
                            null, request.getCategoryId(), request.getWarehouseId(), request.getSearch());
                    if (data.size() > maxRecords) data = data.subList(0, maxRecords);
                    writeMovementReport(baos, request, data, metadata);
                    yield data.size();
                }
                case CRITICAL_ALERTS -> {
                    var data = reportGeneratorService.generateAlertReport(null, null, request.getWarehouseId());
                    writeAlertReport(baos, request, data, metadata);
                    yield data.size();
                }
                case WAREHOUSE_ANALYSIS -> {
                    var data = reportGeneratorService.generateWarehouseAnalysis(request.getWarehouseId());
                    writeWarehouseAnalysis(baos, request, data, metadata);
                    yield data.size();
                }
                case DAILY_RECEIPTS -> {
                    var kpis = reportGeneratorService.generateDailyReceiptReport(
                            request.getWarehouseId(), request.getStartDate(), request.getEndDate());
                    var data = kpis.getRows();
                    if (data.size() > maxRecords) data = data.subList(0, maxRecords);
                    writeDailyReceiptReport(baos, request, data, kpis, metadata);
                    yield data.size();
                }
                default -> throw new IllegalArgumentException("Tipo de reporte no soportado: " + request.getType());
            };
            return new GeneratedReport(baos.toByteArray(), recordCount);
        } catch (Exception e) {
            throw new RuntimeException("Error generando reporte: " + e.getMessage(), e);
        }
    }

    private byte[] buildReportBytes(CreateReportRequest request, Map<String, String> metadata) {
        return buildReport(request, metadata).bytes();
    }

    private void writeStockReport(ByteArrayOutputStream out, CreateReportRequest request,
                                  List<com.visco.backend.reports.models.dtos.StockReportDTO> data,
                                  Map<String, String> metadata) {
        if (request.getFormat() == ReportFormat.PDF) {
            pdfExportService.exportStockReportToPdf(data, request.getName(), metadata, out);
        } else if (request.getFormat() == ReportFormat.EXCEL) {
            excelExportService.exportStockReportToExcel(data, request.getName(), metadata, out);
        } else {
            throw new IllegalArgumentException("Formato no soportado: " + request.getFormat());
        }
    }

    private void writeMovementReport(ByteArrayOutputStream out, CreateReportRequest request,
                                     List<com.visco.backend.reports.models.dtos.MovementReportDTO> data,
                                     Map<String, String> metadata) {
        if (request.getFormat() == ReportFormat.PDF) {
            pdfExportService.exportMovementReportToPdf(data, request.getName(), metadata, out);
        } else if (request.getFormat() == ReportFormat.EXCEL) {
            excelExportService.exportMovementReportToExcel(data, request.getName(), metadata, out);
        } else {
            throw new IllegalArgumentException("Formato no soportado: " + request.getFormat());
        }
    }

    private void writeAlertReport(ByteArrayOutputStream out, CreateReportRequest request,
                                  List<com.visco.backend.reports.models.dtos.AlertReportDTO> data,
                                  Map<String, String> metadata) {
        if (request.getFormat() == ReportFormat.PDF) {
            pdfExportService.exportAlertReportToPdf(data, request.getName(), metadata, out);
        } else if (request.getFormat() == ReportFormat.EXCEL) {
            excelExportService.exportAlertReportToExcel(data, request.getName(), metadata, out);
        } else {
            throw new IllegalArgumentException("Formato no soportado: " + request.getFormat());
        }
    }

    private void writeWarehouseAnalysis(ByteArrayOutputStream out, CreateReportRequest request,
                                        List<com.visco.backend.reports.models.dtos.WarehouseAnalysisDTO> data,
                                        Map<String, String> metadata) {
        if (request.getFormat() == ReportFormat.PDF) {
            pdfExportService.exportWarehouseAnalysisToPdf(data, request.getName(), metadata, out);
        } else if (request.getFormat() == ReportFormat.EXCEL) {
            excelExportService.exportWarehouseAnalysisToExcel(data, request.getName(), metadata, out);
        } else {
            throw new IllegalArgumentException("Formato no soportado: " + request.getFormat());
        }
    }

    private void writeDailyReceiptReport(ByteArrayOutputStream out, CreateReportRequest request,
                                          List<DailyReceiptReportDTO> data,
                                          DailyReceiptReportKPIs kpis,
                                          Map<String, String> metadata) {
        if (request.getFormat() == ReportFormat.PDF) {
            pdfExportService.exportDailyReceiptReportToPdf(data, kpis, request.getName(), metadata, out);
        } else if (request.getFormat() == ReportFormat.EXCEL) {
            excelExportService.exportDailyReceiptReportToExcel(data, kpis, request.getName(), metadata, out);
        } else {
            throw new IllegalArgumentException("Formato no soportado: " + request.getFormat());
        }
    }

    /**
     * Soft-deletes a report. No file to remove on disk.
     */
    @Transactional
    public void deleteReport(Long id) {
        Report report = reportRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Reporte no encontrado: " + id));
        report.setActive(false);
        reportRepository.save(report);
    }

    public List<ScheduledReportDTO> getScheduledReports() {
        return scheduledReportRepository.findAllByOrderByCreatedAtDesc().stream()
                .map(this::toScheduledDTO)
                .collect(Collectors.toList());
    }

    @Transactional
    public ScheduledReportDTO createScheduledReport(CreateScheduledReportRequest request) {
        LocalDateTime nextExecution = DateUtils.calculateNextExecution(
                request.getScheduleTime(), request.getScheduleDayOfWeek(), request.getScheduleDay());

        ScheduledReport sr = ScheduledReport.builder()
                .name(request.getName())
                .reportType(request.getReportType())
                .frequency(request.getFrequency())
                .recipientEmails(request.getRecipientEmails())
                .filterConfig(request.getFilterConfig())
                .format(request.getFormat())
                .scheduleTime(request.getScheduleTime())
                .scheduleDayOfWeek(request.getScheduleDayOfWeek())
                .scheduleDay(request.getScheduleDay())
                .nextExecutionAt(nextExecution)
                .enabled(true)
                .build();

        sr = scheduledReportRepository.save(sr);
        return toScheduledDTO(sr);
    }

    @Transactional
    public ScheduledReportDTO updateScheduledReport(Long id, UpdateScheduledReportRequest request) {
        ScheduledReport sr = scheduledReportRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Reporte programado no encontrado: " + id));

        if (request.getName() != null) sr.setName(request.getName());
        if (request.getReportType() != null) sr.setReportType(request.getReportType());
        if (request.getFrequency() != null) sr.setFrequency(request.getFrequency());
        if (request.getRecipientEmails() != null) sr.setRecipientEmails(request.getRecipientEmails());
        if (request.getFilterConfig() != null) sr.setFilterConfig(request.getFilterConfig());
        if (request.getFormat() != null) sr.setFormat(request.getFormat());
        if (request.getScheduleTime() != null) sr.setScheduleTime(request.getScheduleTime());
        if (request.getScheduleDayOfWeek() != null) sr.setScheduleDayOfWeek(request.getScheduleDayOfWeek());
        if (request.getScheduleDay() != null) sr.setScheduleDay(request.getScheduleDay());
        if (request.getEnabled() != null) sr.setEnabled(request.getEnabled());

        LocalDateTime nextExec = DateUtils.calculateNextExecution(
                sr.getScheduleTime(), sr.getScheduleDayOfWeek(), sr.getScheduleDay());
        sr.setNextExecutionAt(nextExec);

        sr = scheduledReportRepository.save(sr);
        return toScheduledDTO(sr);
    }

    @Transactional
    public void deleteScheduledReport(Long id) {
        ScheduledReport sr = scheduledReportRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Reporte programado no encontrado: " + id));
        scheduledReportRepository.delete(sr);
    }

    @Transactional
    public ReportDTO executeScheduledReport(Long id) {
        ScheduledReport sr = scheduledReportRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Reporte programado no encontrado: " + id));

        CreateReportRequest request = new CreateReportRequest();
        request.setName(sr.getName());
        request.setType(sr.getReportType());
        request.setFormat(sr.getFormat());
        request.setStartDate(LocalDateTime.now().minusDays(30));
        request.setEndDate(LocalDateTime.now());

        var filters = sr.getFilterConfig();
        if (filters != null) {
            try {
                Map<String, Object> additional = objectMapper.readValue(filters, Map.class);
                request.setAdditionalFilters(additional);
            } catch (Exception e) {
                log.warn("Could not parse filter config", e);
            }
        }

        ReportDTO result = generateReport(request, "scheduler");

        sr.setLastExecutedAt(LocalDateTime.now());
        LocalDateTime nextExec = DateUtils.calculateNextExecution(
                sr.getScheduleTime(), sr.getScheduleDayOfWeek(), sr.getScheduleDay());
        sr.setNextExecutionAt(nextExec);
        scheduledReportRepository.save(sr);

        return result;
    }

    @Transactional(readOnly = true)
    public ReportAnalyticsDTO getReportAnalytics() {
        long totalReports = reportRepository.countByActiveTrue();
        long totalScheduled = scheduledReportRepository.count();
        long completedReports = reportRepository.countByStatusAndActiveTrue(ReportStatus.COMPLETED);
        long failedReports = reportRepository.countByStatusAndActiveTrue(ReportStatus.FAILED);
        long pendingReports = reportRepository.countByStatusAndActiveTrue(ReportStatus.PENDING);
        long totalRecordsExported = reportRepository.sumCompletedRecordCount();

        Map<String, Long> reportsByType = reportRepository.countActiveByType().stream()
                .collect(Collectors.toMap(
                        row -> ((ReportType) row[0]).name(),
                        row -> (Long) row[1]
                ));

        Map<String, Long> reportsByStatus = reportRepository.countActiveByStatus().stream()
                .collect(Collectors.toMap(
                        row -> ((ReportStatus) row[0]).name(),
                        row -> (Long) row[1]
                ));

        LocalDateTime sixMonthsAgo = LocalDateTime.now()
                .minusMonths(6)
                .withDayOfMonth(1)
                .withHour(0)
                .withMinute(0)
                .withSecond(0);

        List<ReportAnalyticsDTO.MonthlyCount> monthlyTrend = reportRepository
                .countByMonthSince(sixMonthsAgo)
                .stream()
                .map(row -> {
                    java.sql.Timestamp ts = (java.sql.Timestamp) row[0];
                    long count = (Long) row[1];
                    return ReportAnalyticsDTO.MonthlyCount.builder()
                            .month(ts.toString().substring(0, 7))
                            .count(count)
                            .build();
                })
                .collect(Collectors.toList());

        return ReportAnalyticsDTO.builder()
                .totalReports(totalReports)
                .totalScheduledReports(totalScheduled)
                .completedReports(completedReports)
                .failedReports(failedReports)
                .pendingReports(pendingReports)
                .totalRecordsExported(totalRecordsExported)
                .reportsByType(reportsByType)
                .reportsByStatus(reportsByStatus)
                .monthlyTrend(monthlyTrend)
                .build();
    }

    private ReportDTO toDTO(Report report) {
        return ReportDTO.builder()
                .id(report.getId())
                .name(report.getName())
                .description(report.getDescription())
                .type(report.getType())
                .status(report.getStatus())
                .format(report.getFormat())
                .generatedAt(report.getGeneratedAt())
                .startDate(report.getStartDate())
                .endDate(report.getEndDate())
                .warehouseId(report.getWarehouseId())
                .categoryId(report.getCategoryId())
                .search(report.getSearch())
                .recordCount(report.getRecordCount())
                .fileSize(report.getFileSize())
                .filePath(report.getFilePath())
                .createdBy(report.getCreatedBy())
                .createdAt(report.getCreatedAt())
                .build();
    }

    private ScheduledReportDTO toScheduledDTO(ScheduledReport sr) {
        return ScheduledReportDTO.builder()
                .id(sr.getId())
                .name(sr.getName())
                .reportType(sr.getReportType())
                .frequency(sr.getFrequency())
                .recipientEmails(sr.getRecipientEmails())
                .filterConfig(sr.getFilterConfig())
                .format(sr.getFormat())
                .scheduleTime(sr.getScheduleTime())
                .scheduleDayOfWeek(sr.getScheduleDayOfWeek())
                .scheduleDay(sr.getScheduleDay())
                .lastExecutedAt(sr.getLastExecutedAt())
                .nextExecutionAt(sr.getNextExecutionAt())
                .enabled(sr.getEnabled())
                .createdAt(sr.getCreatedAt())
                .build();
    }
}
